name: Build Android APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Buildozer global directory
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ runner.os }}-${{ steps.get-date.outputs.date }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev sqlite3 bzip2 libbz2-dev zlib1g-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev
        pip install --upgrade pip
        pip install buildozer cython git+https://github.com/kivy/kivy.git@master

    - name: Build with Buildozer
      run: |
        yes | buildozer android debug
      env:
        ACCEPT_SDK_LICENSE: "y"

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mallakhamb-Academy-Android-APK
        path: bin/*.apk
